name: CI

on:
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ 'main' ]


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Kover
        run: ./gradlew koverXmlReport

      - name: Upload coverage to Codecov
        if: ${{ !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'renovate/') }}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
