name: CI

on:
  push:
    branches: [ 'main' ]

  pull_request:
    branches: [ 'main' ]


concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Kover
        run: ./gradlew koverXmlReport

      - name: Upload coverage to Codecov
        if: ${{ !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'renovate/') }}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: List test result reports
        if: ${{ !cancelled() && !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'renovate/') }}
        id: reports
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const globber = await glob.create("build/test-results/test/*.xml");
            const files = await globber.glob();
            
            return files.join(",");

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'renovate/') }}
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          files: ${{ steps.reports.outputs.result }}
          token: ${{ secrets.CODECOV_TOKEN }}
